# Generated by Django 3.1.5 on 2021-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210116_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='copyrighted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='hidden_to_others',
            field=models.BooleanField(default=True),
        ),
    ]
